#[derive(Debug)]
pub enum CurrencyCode {
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BOV,
    BRL,
    BSD,
    BTN,
    BWP,
    BYN,
    BZD,
    CAD,
    CDF,
    CHE,
    CHF,
    CHW,
    CLF,
    CLP,
    CNY,
    COP,
    COU,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    INR,
    IQD,
    IRR,
    ISK,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRU,
    MUR,
    MVR,
    MWK,
    MXN,
    MXV,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SLL,
    SOS,
    SRD,
    SSP,
    STN,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    USN,
    UYI,
    UYU,
    UYW,
    UZS,
    VES,
    VND,
    VUV,
    WST,
    XAF,
    XAG,
    XAU,
    XBA,
    XBB,
    XBC,
    XBD,
    XCD,
    XDR,
    XOF,
    XPD,
    XPF,
    XPT,
    XSU,
    XTS,
    XUA,
    XXX,
    YER,
    ZAR,
    ZMW,
    ZWL,
}

impl std::fmt::Display for CurrencyCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", match self {
        Self::AED => "AED",
        Self::AFN => "AFN",
        Self::ALL => "ALL",
        Self::AMD => "AMD",
        Self::ANG => "ANG",
        Self::AOA => "AOA",
        Self::ARS => "ARS",
        Self::AUD => "AUD",
        Self::AWG => "AWG",
        Self::AZN => "AZN",
        Self::BAM => "BAM",
        Self::BBD => "BBD",
        Self::BDT => "BDT",
        Self::BGN => "BGN",
        Self::BHD => "BHD",
        Self::BIF => "BIF",
        Self::BMD => "BMD",
        Self::BND => "BND",
        Self::BOB => "BOB",
        Self::BOV => "BOV",
        Self::BRL => "BRL",
        Self::BSD => "BSD",
        Self::BTN => "BTN",
        Self::BWP => "BWP",
        Self::BYN => "BYN",
        Self::BZD => "BZD",
        Self::CAD => "CAD",
        Self::CDF => "CDF",
        Self::CHE => "CHE",
        Self::CHF => "CHF",
        Self::CHW => "CHW",
        Self::CLF => "CLF",
        Self::CLP => "CLP",
        Self::CNY => "CNY",
        Self::COP => "COP",
        Self::COU => "COU",
        Self::CRC => "CRC",
        Self::CUC => "CUC",
        Self::CUP => "CUP",
        Self::CVE => "CVE",
        Self::CZK => "CZK",
        Self::DJF => "DJF",
        Self::DKK => "DKK",
        Self::DOP => "DOP",
        Self::DZD => "DZD",
        Self::EGP => "EGP",
        Self::ERN => "ERN",
        Self::ETB => "ETB",
        Self::EUR => "EUR",
        Self::FJD => "FJD",
        Self::FKP => "FKP",
        Self::GBP => "GBP",
        Self::GEL => "GEL",
        Self::GHS => "GHS",
        Self::GIP => "GIP",
        Self::GMD => "GMD",
        Self::GNF => "GNF",
        Self::GTQ => "GTQ",
        Self::GYD => "GYD",
        Self::HKD => "HKD",
        Self::HNL => "HNL",
        Self::HRK => "HRK",
        Self::HTG => "HTG",
        Self::HUF => "HUF",
        Self::IDR => "IDR",
        Self::ILS => "ILS",
        Self::INR => "INR",
        Self::IQD => "IQD",
        Self::IRR => "IRR",
        Self::ISK => "ISK",
        Self::JMD => "JMD",
        Self::JOD => "JOD",
        Self::JPY => "JPY",
        Self::KES => "KES",
        Self::KGS => "KGS",
        Self::KHR => "KHR",
        Self::KMF => "KMF",
        Self::KPW => "KPW",
        Self::KRW => "KRW",
        Self::KWD => "KWD",
        Self::KYD => "KYD",
        Self::KZT => "KZT",
        Self::LAK => "LAK",
        Self::LBP => "LBP",
        Self::LKR => "LKR",
        Self::LRD => "LRD",
        Self::LSL => "LSL",
        Self::LYD => "LYD",
        Self::MAD => "MAD",
        Self::MDL => "MDL",
        Self::MGA => "MGA",
        Self::MKD => "MKD",
        Self::MMK => "MMK",
        Self::MNT => "MNT",
        Self::MOP => "MOP",
        Self::MRU => "MRU",
        Self::MUR => "MUR",
        Self::MVR => "MVR",
        Self::MWK => "MWK",
        Self::MXN => "MXN",
        Self::MXV => "MXV",
        Self::MYR => "MYR",
        Self::MZN => "MZN",
        Self::NAD => "NAD",
        Self::NGN => "NGN",
        Self::NIO => "NIO",
        Self::NOK => "NOK",
        Self::NPR => "NPR",
        Self::NZD => "NZD",
        Self::OMR => "OMR",
        Self::PAB => "PAB",
        Self::PEN => "PEN",
        Self::PGK => "PGK",
        Self::PHP => "PHP",
        Self::PKR => "PKR",
        Self::PLN => "PLN",
        Self::PYG => "PYG",
        Self::QAR => "QAR",
        Self::RON => "RON",
        Self::RSD => "RSD",
        Self::RUB => "RUB",
        Self::RWF => "RWF",
        Self::SAR => "SAR",
        Self::SBD => "SBD",
        Self::SCR => "SCR",
        Self::SDG => "SDG",
        Self::SEK => "SEK",
        Self::SGD => "SGD",
        Self::SHP => "SHP",
        Self::SLL => "SLL",
        Self::SOS => "SOS",
        Self::SRD => "SRD",
        Self::SSP => "SSP",
        Self::STN => "STN",
        Self::SVC => "SVC",
        Self::SYP => "SYP",
        Self::SZL => "SZL",
        Self::THB => "THB",
        Self::TJS => "TJS",
        Self::TMT => "TMT",
        Self::TND => "TND",
        Self::TOP => "TOP",
        Self::TRY => "TRY",
        Self::TTD => "TTD",
        Self::TWD => "TWD",
        Self::TZS => "TZS",
        Self::UAH => "UAH",
        Self::UGX => "UGX",
        Self::USD => "USD",
        Self::USN => "USN",
        Self::UYI => "UYI",
        Self::UYU => "UYU",
        Self::UYW => "UYW",
        Self::UZS => "UZS",
        Self::VES => "VES",
        Self::VND => "VND",
        Self::VUV => "VUV",
        Self::WST => "WST",
        Self::XAF => "XAF",
        Self::XAG => "XAG",
        Self::XAU => "XAU",
        Self::XBA => "XBA",
        Self::XBB => "XBB",
        Self::XBC => "XBC",
        Self::XBD => "XBD",
        Self::XCD => "XCD",
        Self::XDR => "XDR",
        Self::XOF => "XOF",
        Self::XPD => "XPD",
        Self::XPF => "XPF",
        Self::XPT => "XPT",
        Self::XSU => "XSU",
        Self::XTS => "XTS",
        Self::XUA => "XUA",
        Self::XXX => "XXX",
        Self::YER => "YER",
        Self::ZAR => "ZAR",
        Self::ZMW => "ZMW",
        Self::ZWL => "ZWL",
        })
    }
}